### ISSUE TITLE
Question Regarding Missing Files in AudioSet-2M for SpatialSoundQA

### ISSUE THREAD

**Issue by K0hoo** [zszheng147/Spatial-AST#3]
Thank you for providing the SpatialSoundQA dataset and your insightful work in the paper BAT: Learning to Reason about Spatial Sounds with Large Language Models.

I am currently working on replicating your experiments and have downloaded the refined AudioSet-2M using the unbalance_train.json file you provided. However, I found that many of the files are no longer available for download on YouTube.

Would it be possible to access the fully refined AudioSet-2M dataset that you used for SpatialSoundQA?

Thank you for your assistance.

**Comment by zszheng147** [comment]
Hi Younghoo,

Thanks for your interest. Unfortunately, Audioset-2M is too large to put on the web for people to download, but I think as long as you can download most files (1M or larger), you should be able to replicate the experiment.

Thank you,
Zhisheng
